development:
  adapter: postgresql
  database: pcol_dev
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: pcol_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pcol_prod
  pool: 5
  timeout: 5000